namespace OpenRealSense {
    public enum StreamType {
        Depth = 0, ///Native stream of depth data produced by RealSense device
        Color = 1, ///Native stream of color data captured by RealSense device
        Infrared = 2, ///Native stream of infrared data captured by RealSense device
        Infrared2 = 3, ///Native stream of infrared data captured from a second viewpoint by RealSense device
        FishEye = 4, ///Native stream fish-eye (wide) data captured from the dedicate motion camera
        Points = 5, ///Synthetic stream containing point cloud data generated by deprojecting the depth image
        RectifiedColor = 6, ///Synthetic stream containing undistorted color data with no extrinsic rotation from the depth stream
        ColorAlignedToDepth = 7, ///Synthetic stream containing color data but sharing intrinsics of depth stream
        Infrared2AlignedToDepth = 8, ///Synthetic stream containing second viewpoint infrared data but sharing intrinsics of depth stream
        DepthAlignedToColor = 9, ///Synthetic stream containing depth data but sharing intrinsics of color stream
        DepthAlignedToRectifiedColor = 10, ///Synthetic stream containing depth data but sharing intrinsics of rectified color stream
        DepthAlignedToInfrared2 = 11 ///Synthetic stream containing depth data but sharing intrinsics of second viewpoint infrared stream
    }
}
